# Generated by Django 3.2.3 on 2021-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('summary', models.CharField(max_length=2000)),
                ('education', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=5000)),
            ],
        ),
    ]
