# Generated by Django 3.2.3 on 2021-05-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcv',
            name='current_role',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
