# Generated by Django 3.2.3 on 2021-05-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_modelcv_current_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcv',
            old_name='education',
            new_name='university',
        ),
    ]
