# Generated by Django 3.2.3 on 2021-05-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_rename_education_modelcv_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcv',
            name='skills',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='modelcv',
            name='summary',
            field=models.TextField(max_length=2000),
        ),
    ]
